Inserção do conteúdo inicial sobre Linux Containers
redhat-sa-brazil/workshop-openshift pull request #66
Opened 2019-11-05 22:05 UTC by levenhagen

**Qual o tipo desse PR (bug, cleaup, feature)?**:

Feature

**O que esse PR faz, ou porquê é necessário?**:
 
Alteração do arquivo sidebar.md para inclusão dos novos tópicos adicionados no capítulo de Linux Container, bem como inclusão do conteúdo nos novos tópicos.

**Qual, ou quais, Issues esse PR endereça?**:

Fixes #49

2019-11-06 12:44 UTC, davivcgarcia requested changes
Show! Alguns comentários:

- Alguns conteúdos ficaram bastante extensos, achava melhor tentar ser menos prolixo;
- As sessões de introdução e imagens poderiam ser condensadas em uma só;

O conteúdo ficou ótimo, mas senti que algumas sessões ficaram muito verbosas e falta os exercícios entre as explicações. A ideia do material é fornecer um exercícios guiado, nos moldes da versão v3. Consegue adicionar?

2019-11-06 12:44 UTC, davivcgarcia commented on docs/_sidebar.md
> +  - [RedHat Quay e Docker Hub](/linux-containers/registros.md)
Porque você colocou `.md` nesses links, e não deixou como o da introdução?

2019-11-06 12:44 UTC, davivcgarcia commented on docs/linux-containers/imagens.md
> +e o provisionamento de imagens.
Acho que ficou um pouco prolixo a explicação, podemos tentar resumir.
Na parte que exemplifica dependências, trocaria a frase para:

> A imagem é um pacote de sistema de arquivos que contém todas as dependências necessárias para executar
um processo: **arquivos de configuração**, **pacotes de sistema**, **bibliotecas** e etc.

2019-11-06 12:44 UTC, davivcgarcia commented on docs/linux-containers/imagens.md
> +
Acho que ficou faltando colocar uma ilustração exemplificando uma imagem de container, e explicar a questão delas serem constituidas por camadas.

2019-11-06 12:44 UTC, davivcgarcia commented on docs/linux-containers/introducao.md
> +de banco de dados.
Muuuiiitttoooo extenso... =D

2019-11-06 12:44 UTC, davivcgarcia commented on docs/linux-containers/imagens.md
> +<https://registry.fedoraproject.org>
Faltou mencionar o quay.io, que é o melhor deles... =)

2019-11-06 19:32 UTC, jlassery commented
Davi, as correções foram feitas. Pode checar , por favor ?  @davivcgarcia

2019-11-06 19:48 UTC, levenhagen commented
Ainda será feito um commit para inserção dos exerc

> Show! Alguns comentários:
> 
> * Alguns conteúdos ficaram bastante extensos, achava melhor tentar ser menos prolixo;
> * As sessões de introdução e imagens poderiam ser condensadas em uma só;
> 
> O conteúdo ficou ótimo, mas senti que algumas sessões ficaram muito verbosas e falta os exercícios entre as explicações. A ideia do material é fornecer um exercícios guiado, nos moldes da versão v3. Consegue adicionar?

Ainda será feito um commit para inserção dos exercícios conforme requisitado acima.

2019-11-07 01:35 UTC, davivcgarcia commented
> Davi, as correções foram feitas. Pode checar , por favor ?

Validei e alguns dos pontos que eu coloquei lá em cima ainda não foram corrigidos. Essa branch só vai ser `merge` com a `develop` quando o capitulo atender 100% dos requisitos da issue #49.

2019-11-07 15:51 UTC, jlassery commented
> > Davi, as correções foram feitas. Pode checar , por favor ?
> 
> Validei e alguns dos pontos que eu coloquei lá em cima ainda não foram corrigidos. Essa branch só vai ser `merge` com a `develop` quando o capitulo atender 100% dos requisitos da issue #49.

Foram feitas algumas alterações, incluindo laboratórios hands on para atender 100% os requisitos da issue #49

2019-11-11 15:06 UTC, jlassery commented on docs/_sidebar.md
> +  - [RedHat Quay e Docker Hub](/linux-containers/registros.md)
Modificado!

2019-11-11 15:07 UTC, jlassery commented on docs/linux-containers/imagens.md
> +
Imagem colocada.

2019-11-11 15:07 UTC, jlassery commented on docs/linux-containers/introducao.md
> +de banco de dados.
Texto resumido.

2019-11-11 15:07 UTC, jlassery commented on docs/linux-containers/imagens.md
> +<https://registry.fedoraproject.org>
Mencionado.

2019-11-11 15:30 UTC, jlassery commented on docs/linux-containers/imagens.md
> +e o provisionamento de imagens.
Modificado. Atualização estará disponível no próximo commit.

2019-11-11 16:20 UTC, jlassery commented on docs/linux-containers/imagens.md
> +e o provisionamento de imagens.
Modificado e commitado

2019-11-12 21:52 UTC, jlassery commented
Davi,  finalizamos nossa versão final da issue #49 . Pode checar, por gentileza. @davivcgarcia

2020-01-27 20:35 UTC, closed without merging